### ISSUE TITLE
maintenance assignments, workflow, and guidelines

### ISSUE THREAD

**Issue by olets** [vigetlabs/tailwindcss-plugins#27]
@ten1seven

cc @gregkohn @jeremyfrank as primary contributors and historical de-facto gatekeepers

Though the Viget front-end team relies on it for every project, we haven't been great about maintaining tailwindcss-plugins (not a dig at the historical de-factor gatekeepers). As of this writing we have in the review pipeline:

- a new plugin proposal from April 2020
    #6
- a bugfix from November 2020
    #20
- a new PR updating to TW 2.x, which was first released November 2020
    #23
- (and some other new PRs not relevant to this issue)

Having clear approval and maintenance responsibilities would increase the likelihood that the package stays in good shape. At best it might encourage more people to contribute.

I recommend we decide and document (publicly or internally)

1. who is responsible for approving documentation changes, style changes, and refactors; and turnaround time expectations*†
1. who is responsible for approving plugin submissions; and turnaround time expectations*†
1. who is responsible for general maintenance (dependency upgrades, etc) and their maintenance cycle
1. guidelines for how inclusive/exclusive we want to be when considering plugin proposals

    \* Does not imply it needs to be _fast_
    † Perhaps falling back into (3)'s responsibilities if still open at their next maintenance cycle

Maybe we won't decide and document those exact things. Deciding and documenting something would set users' and contributors' expectations.

**Comment by jeremyfrank** [comment]
@olets Thanks for rounding this stuff up. Yes the plugins repo definitely needs some cleanup, maintenance and additional guidelines and documentation added.

@ten1seven Can we add some time for me in RPM the first week of October?  I could start working through some of this stuff then. That's when AHIP phase 2 starts and my hours go down slightly (enough to have time for this).

**Comment by ten1seven** [comment]
@jeremyfrank I grabbed 4 hours as PD the week of Oct 4. Combined with your director time you could have upwards of 8+ hours for this.

@olets thanks for pulling this together. Would you be up for putting together a process?

**Comment by olets** [comment]
> Would you be up for putting together a process?

Absolutely — I can put team hours into this. @jeremyfrank I put a chat on our calendars for the first week of October.

**Comment by gregkohn** [comment]
I think whatever process we are talking about should be generalized to all overhead repos the team uses, I don't see anything in particular about this one that merits a unique process. And really, I think the main process we need is just to formalize these responsibilities (1-3 of Henry's thoughts). This repo, for example, isn't that behind in terms of the time needed to update it -- it just fell through the cracks. We should track and be mindful of the repos we use across projects -- FedPack, Craft base module are others -- and set up expectations for maintenance, be it monthly or whatever.
